[deployment]
image = "internal/backend:sha183ea69727896fe7cb777dd76baf7b477d5aa8ac"
expose = true
id = "248778ab-62aa-46ac-bac1-16b4c40570c0"

[services.postgres]
enabled = true

[services.minio]
enabled = true
