[deployment]
id = "ed9161ea-12f1-45fd-b5d2-c411c0cadef1"
image = "internal/backend:sha0bebde69c7fa98085d09be74d05ee18145831c1b"
expose = true

[services.postgres]
enabled=true

[services.minio]
enabled=true