networks:
  bitswan_network:
    external: true
services:
  demo-meeting-form-backend-0f13-live-dev:
    container_name: demo-meeting-form-backend-0f13-live-dev
    environment:
      BITSWAN_ALLOWED_GROUP: /NikitaPlay
      BITSWAN_AUTOMATION_STAGE: live-dev
      BITSWAN_DEPLOYMENT_CONTEXT: demo-wt-demo-live-dev
      BITSWAN_DEPLOYMENT_ID: backend-wt-demo-demo-live-dev
      BITSWAN_DEPLOY_CHECKSUM: live-dev
      BITSWAN_DEPLOY_TIME: '2026-06-08T16:14:41.035457Z'
      BITSWAN_GITOPS_DOMAIN: nikita-sandbox.bswn.io
      BITSWAN_URL_TEMPLATE: https://demo-meeting-form-{name}-0f13-live-dev.nikita-sandbox.bswn.io
      BITSWAN_WORKSPACE_NAME: demo-meeting-form
      KEYCLOAK_ISSUER_URL: https://keycloak.bitswan.ai/realms/master
      KEYCLOAK_REALM: master
      KEYCLOAK_URL: https://keycloak.bitswan.ai
      POSTGRES_DB: postgres_wt_demo
      UPDATE_CA_CERTIFICATES: 'true'
    image: bitswan/pipeline-runtime-environment:latest
    labels:
      gitops.automation_name: backend
      gitops.certs.enabled: 'true'
      gitops.context: wt-demo-demo
      gitops.deployment_id: backend-wt-demo-demo-live-dev
      gitops.intended_exposed: 'false'
      gitops.stage: live-dev
      gitops.workspace: demo-meeting-form
    networks:
    - bitswan_network
    restart: always
    ulimits:
      nofile:
        hard: 65536
        soft: 65536
    volumes:
    - /root/.config/bitswan/certauthorities:/usr/local/share/ca-certificates/custom:ro
    - /root/.config/bitswan/workspaces/demo-meeting-form/workspace/worktrees/demo/demo/backend:/opt/pipelines:ro
  demo-meeting-form-backend-2a97-dev:
    container_name: demo-meeting-form-backend-2a97-dev
    env_file:
    - /gitops/secrets/postgres-dev
    - /gitops/secrets/minio-dev
    environment:
      BITSWAN_ALLOWED_GROUP: /NikitaPlay
      BITSWAN_AUTOMATION_STAGE: dev
      BITSWAN_AUTOMATION_URL: https://demo-meeting-form-backend-2a97-dev.nikita-sandbox.bswn.io
      BITSWAN_DEPLOYMENT_CONTEXT: demo-dev
      BITSWAN_DEPLOYMENT_ID: backend-demo-dev
      BITSWAN_DEPLOY_CHECKSUM: a58c69500688789300bec1d97e284a441f3dbdca
      BITSWAN_DEPLOY_TIME: '2026-06-08T16:14:40.523200Z'
      BITSWAN_GITOPS_DOMAIN: nikita-sandbox.bswn.io
      BITSWAN_URL_PREFIX: https://demo-meeting-form-
      BITSWAN_URL_SUFFIX: .nikita-sandbox.bswn.io
      BITSWAN_URL_TEMPLATE: https://demo-meeting-form-{name}-2a97-dev.nikita-sandbox.bswn.io
      BITSWAN_WORKSPACE_NAME: demo-meeting-form
      KEYCLOAK_ISSUER_URL: https://keycloak.bitswan.ai/realms/master
      KEYCLOAK_REALM: master
      KEYCLOAK_URL: https://keycloak.bitswan.ai
      UPDATE_CA_CERTIFICATES: 'true'
    image: internal/demo-meeting-form-demo-backend:sha9a385567378f23933128c6ce8896bafee1271d85
    labels:
      gitops.automation_name: backend
      gitops.certs.enabled: 'true'
      gitops.context: demo
      gitops.deployment_id: backend-demo-dev
      gitops.intended_exposed: 'true'
      gitops.stage: dev
      gitops.workspace: demo-meeting-form
    networks:
      bitswan_network:
        aliases:
        - demo-meeting-form-backend-2a97-dev.nikita-sandbox.bswn.io
    restart: always
    ulimits:
      nofile:
        hard: 65536
        soft: 65536
    volumes:
    - /root/.config/bitswan/certauthorities:/usr/local/share/ca-certificates/custom:ro
    - /root/.config/bitswan/workspaces/demo-meeting-form/gitops/a58c69500688789300bec1d97e284a441f3dbdca:/app/:ro
  demo-meeting-form-backend-2a97-production:
    container_name: demo-meeting-form-backend-2a97-production
    env_file:
    - /gitops/secrets/postgres
    - /gitops/secrets/minio
    environment:
      BITSWAN_ALLOWED_GROUP: /NikitaPlay
      BITSWAN_AUTOMATION_STAGE: production
      BITSWAN_AUTOMATION_URL: https://demo-meeting-form-backend-2a97-production.nikita-sandbox.bswn.io
      BITSWAN_DEPLOYMENT_CONTEXT: demo
      BITSWAN_DEPLOYMENT_ID: backend-demo
      BITSWAN_DEPLOY_CHECKSUM: ddfd054c3428a4ed3e5732de60f5b8041b413874
      BITSWAN_DEPLOY_TIME: '2026-06-08T16:14:40.314099Z'
      BITSWAN_GITOPS_DOMAIN: nikita-sandbox.bswn.io
      BITSWAN_URL_PREFIX: https://demo-meeting-form-
      BITSWAN_URL_SUFFIX: .nikita-sandbox.bswn.io
      BITSWAN_URL_TEMPLATE: https://demo-meeting-form-{name}-2a97.nikita-sandbox.bswn.io
      BITSWAN_WORKSPACE_NAME: demo-meeting-form
      KEYCLOAK_ISSUER_URL: https://keycloak.bitswan.ai/realms/master
      KEYCLOAK_REALM: master
      KEYCLOAK_URL: https://keycloak.bitswan.ai
      UPDATE_CA_CERTIFICATES: 'true'
    image: internal/demo-meeting-form-demo-backend:sha9a385567378f23933128c6ce8896bafee1271d85
    labels:
      gitops.automation_name: backend
      gitops.certs.enabled: 'true'
      gitops.context: demo
      gitops.deployment_id: backend-demo
      gitops.intended_exposed: 'true'
      gitops.stage: production
      gitops.workspace: demo-meeting-form
    networks:
      bitswan_network:
        aliases:
        - demo-meeting-form-backend-2a97-production.nikita-sandbox.bswn.io
    restart: always
    ulimits:
      nofile:
        hard: 65536
        soft: 65536
    volumes:
    - /root/.config/bitswan/certauthorities:/usr/local/share/ca-certificates/custom:ro
    - /root/.config/bitswan/workspaces/demo-meeting-form/gitops/ddfd054c3428a4ed3e5732de60f5b8041b413874:/app/:ro
  demo-meeting-form-backend-2a97-staging:
    container_name: demo-meeting-form-backend-2a97-staging
    env_file:
    - /gitops/secrets/postgres-staging
    - /gitops/secrets/minio-staging
    environment:
      BITSWAN_ALLOWED_GROUP: /NikitaPlay
      BITSWAN_AUTOMATION_STAGE: staging
      BITSWAN_AUTOMATION_URL: https://demo-meeting-form-backend-2a97-staging.nikita-sandbox.bswn.io
      BITSWAN_DEPLOYMENT_CONTEXT: demo-staging
      BITSWAN_DEPLOYMENT_ID: backend-demo-staging
      BITSWAN_DEPLOY_CHECKSUM: ddfd054c3428a4ed3e5732de60f5b8041b413874
      BITSWAN_DEPLOY_TIME: '2026-06-08T16:14:40.787289Z'
      BITSWAN_GITOPS_DOMAIN: nikita-sandbox.bswn.io
      BITSWAN_URL_PREFIX: https://demo-meeting-form-
      BITSWAN_URL_SUFFIX: .nikita-sandbox.bswn.io
      BITSWAN_URL_TEMPLATE: https://demo-meeting-form-{name}-2a97-staging.nikita-sandbox.bswn.io
      BITSWAN_WORKSPACE_NAME: demo-meeting-form
      KEYCLOAK_ISSUER_URL: https://keycloak.bitswan.ai/realms/master
      KEYCLOAK_REALM: master
      KEYCLOAK_URL: https://keycloak.bitswan.ai
      UPDATE_CA_CERTIFICATES: 'true'
    image: internal/demo-meeting-form-demo-backend:sha9a385567378f23933128c6ce8896bafee1271d85
    labels:
      gitops.automation_name: backend
      gitops.certs.enabled: 'true'
      gitops.context: demo
      gitops.deployment_id: backend-demo-staging
      gitops.intended_exposed: 'true'
      gitops.stage: staging
      gitops.workspace: demo-meeting-form
    networks:
      bitswan_network:
        aliases:
        - demo-meeting-form-backend-2a97-staging.nikita-sandbox.bswn.io
    restart: always
    ulimits:
      nofile:
        hard: 65536
        soft: 65536
    volumes:
    - /root/.config/bitswan/certauthorities:/usr/local/share/ca-certificates/custom:ro
    - /root/.config/bitswan/workspaces/demo-meeting-form/gitops/ddfd054c3428a4ed3e5732de60f5b8041b413874:/app/:ro
  demo-meeting-form-backend-2e40-live-dev:
    container_name: demo-meeting-form-backend-2e40-live-dev
    env_file:
    - /gitops/secrets/postgres-dev
    - /gitops/secrets/minio-dev
    environment:
      BITSWAN_ALLOWED_GROUP: /NikitaPlay
      BITSWAN_AUTOMATION_STAGE: live-dev
      BITSWAN_AUTOMATION_URL: https://demo-meeting-form-backend-2e40-live-dev.nikita-sandbox.bswn.io
      BITSWAN_DEPLOYMENT_CONTEXT: demo-wt-demo-new-live-dev
      BITSWAN_DEPLOYMENT_ID: backend-wt-demo-new-demo-live-dev
      BITSWAN_DEPLOY_CHECKSUM: live-dev
      BITSWAN_DEPLOY_TIME: '2026-06-08T16:14:41.193095Z'
      BITSWAN_GITOPS_DOMAIN: nikita-sandbox.bswn.io
      BITSWAN_URL_PREFIX: https://demo-meeting-form-
      BITSWAN_URL_SUFFIX: .nikita-sandbox.bswn.io
      BITSWAN_URL_TEMPLATE: https://demo-meeting-form-{name}-2e40-live-dev.nikita-sandbox.bswn.io
      BITSWAN_WORKSPACE_NAME: demo-meeting-form
      KEYCLOAK_ISSUER_URL: https://keycloak.bitswan.ai/realms/master
      KEYCLOAK_REALM: master
      KEYCLOAK_URL: https://keycloak.bitswan.ai
      POSTGRES_DB: postgres_wt_demo_new
      UPDATE_CA_CERTIFICATES: 'true'
    image: internal/demo-meeting-form-demo-backend:sha9a385567378f23933128c6ce8896bafee1271d85
    labels:
      gitops.automation_name: backend
      gitops.certs.enabled: 'true'
      gitops.context: wt-demo-new-demo
      gitops.deployment_id: backend-wt-demo-new-demo-live-dev
      gitops.intended_exposed: 'true'
      gitops.stage: live-dev
      gitops.workspace: demo-meeting-form
    networks:
      bitswan_network:
        aliases:
        - demo-meeting-form-backend-2e40-live-dev.nikita-sandbox.bswn.io
    restart: always
    ulimits:
      nofile:
        hard: 65536
        soft: 65536
    volumes:
    - /root/.config/bitswan/certauthorities:/usr/local/share/ca-certificates/custom:ro
    - /root/.config/bitswan/workspaces/demo-meeting-form/workspace/worktrees/demo-new/demo/backend:/app/:ro
  demo-meeting-form-internal-frontend-0f13-live-dev:
    container_name: demo-meeting-form-internal-frontend-0f13-live-dev
    environment:
      BITSWAN_ALLOWED_GROUP: /NikitaPlay
      BITSWAN_AUTOMATION_STAGE: live-dev
      BITSWAN_DEPLOYMENT_CONTEXT: demo-wt-demo-live-dev
      BITSWAN_DEPLOYMENT_ID: internal-frontend-wt-demo-demo-live-dev
      BITSWAN_DEPLOY_CHECKSUM: live-dev
      BITSWAN_DEPLOY_TIME: '2026-06-08T16:14:42.584005Z'
      BITSWAN_GITOPS_DOMAIN: nikita-sandbox.bswn.io
      BITSWAN_URL_TEMPLATE: https://demo-meeting-form-{name}-0f13-live-dev.nikita-sandbox.bswn.io
      BITSWAN_WORKSPACE_NAME: demo-meeting-form
      KEYCLOAK_ISSUER_URL: https://keycloak.bitswan.ai/realms/master
      KEYCLOAK_REALM: master
      KEYCLOAK_URL: https://keycloak.bitswan.ai
      POSTGRES_DB: postgres_wt_demo
      UPDATE_CA_CERTIFICATES: 'true'
    image: bitswan/pipeline-runtime-environment:latest
    labels:
      gitops.automation_name: internal-frontend
      gitops.certs.enabled: 'true'
      gitops.context: wt-demo-demo
      gitops.deployment_id: internal-frontend-wt-demo-demo-live-dev
      gitops.intended_exposed: 'false'
      gitops.stage: live-dev
      gitops.workspace: demo-meeting-form
    networks:
    - bitswan_network
    restart: always
    ulimits:
      nofile:
        hard: 65536
        soft: 65536
    volumes:
    - /root/.config/bitswan/certauthorities:/usr/local/share/ca-certificates/custom:ro
    - /root/.config/bitswan/workspaces/demo-meeting-form/workspace/worktrees/demo/demo/internal-frontend:/opt/pipelines:ro
  demo-meeting-form-internal-frontend-2a97-production:
    container_name: demo-meeting-form-internal-frontend-2a97-production
    environment:
      BITSWAN_ALLOWED_GROUP: /NikitaPlay
      BITSWAN_AUTOMATION_STAGE: production
      BITSWAN_AUTOMATION_URL: https://demo-meeting-form-internal-frontend-2a97-production.nikita-sandbox.bswn.io
      BITSWAN_DEPLOYMENT_CONTEXT: demo
      BITSWAN_DEPLOYMENT_ID: internal-frontend-demo
      BITSWAN_DEPLOY_CHECKSUM: 80a574ca70a320e749f5d3a3ffcece16a22fcc60
      BITSWAN_DEPLOY_TIME: '2026-06-08T16:14:41.468662Z'
      BITSWAN_GITOPS_DOMAIN: nikita-sandbox.bswn.io
      BITSWAN_URL_PREFIX: https://demo-meeting-form-
      BITSWAN_URL_SUFFIX: .nikita-sandbox.bswn.io
      BITSWAN_URL_TEMPLATE: https://demo-meeting-form-{name}-2a97.nikita-sandbox.bswn.io
      BITSWAN_WORKSPACE_NAME: demo-meeting-form
      KEYCLOAK_ISSUER_URL: https://keycloak.bitswan.ai/realms/master
      KEYCLOAK_REALM: master
      KEYCLOAK_URL: https://keycloak.bitswan.ai
      OAUTH2_PROXY_ALLOWED_GROUPS: /NikitaPlay/admin
      OAUTH2_PROXY_CLIENT_ID: workspace-008e5dc9-ad56-422b-9b7a-38c709e6ebba-internal-frontend-demo-client
      OAUTH2_PROXY_CLIENT_SECRET: tVRWwQVVyN9YYAu1brA3YPSbluXGxOrm
      OAUTH2_PROXY_CODE_CHALLENGE_METHOD: S256
      OAUTH2_PROXY_COOKIE_REFRESH: 14m
      OAUTH2_PROXY_COOKIE_SECRET: nqxxrX0JXVzuSyVpRIzNCy44WtR0sUWK
      OAUTH2_PROXY_EMAIL_DOMAINS: '*'
      OAUTH2_PROXY_HTTP_ADDRESS: 0.0.0.0:9999
      OAUTH2_PROXY_OIDC_GROUPS_CLAIM: group_membership
      OAUTH2_PROXY_OIDC_ISSUER_URL: https://keycloak.bitswan.ai/realms/master
      OAUTH2_PROXY_PASS_ACCESS_TOKEN: 'true'
      OAUTH2_PROXY_PROVIDER: keycloak-oidc
      OAUTH2_PROXY_REDIRECT_URL: https://demo-meeting-form-internal-frontend-2a97-production.nikita-sandbox.bswn.io/oauth2/callback
      OAUTH2_PROXY_SCOPE: openid email profile
      OAUTH2_PROXY_SET_XAUTHREQUEST: 'true'
      OAUTH2_PROXY_SKIP_PROVIDER_BUTTON: 'true'
      OAUTH2_PROXY_UPSTREAMS: http://127.0.0.1:8080
      OAUTH_ENABLED: 'true'
      UPDATE_CA_CERTIFICATES: 'true'
    image: internal/demo-meeting-form-demo-internal-frontend:shaff19929f41f3c3a34d4098aa7d1394bb60b3ac98
    labels:
      gitops.automation_name: internal-frontend
      gitops.certs.enabled: 'true'
      gitops.context: demo
      gitops.deployment_id: internal-frontend-demo
      gitops.intended_exposed: 'true'
      gitops.oauth2.enabled: 'true'
      gitops.stage: production
      gitops.workspace: demo-meeting-form
    networks:
      bitswan_network:
        aliases:
        - demo-meeting-form-internal-frontend-2a97-production.nikita-sandbox.bswn.io
    restart: always
    ulimits:
      nofile:
        hard: 65536
        soft: 65536
    volumes:
    - /root/.config/bitswan/certauthorities:/usr/local/share/ca-certificates/custom:ro
    - /root/.config/bitswan/workspaces/demo-meeting-form/gitops/80a574ca70a320e749f5d3a3ffcece16a22fcc60:/app/:ro
  demo-meeting-form-internal-frontend-2a97-staging:
    container_name: demo-meeting-form-internal-frontend-2a97-staging
    environment:
      BITSWAN_ALLOWED_GROUP: /NikitaPlay
      BITSWAN_AUTOMATION_STAGE: staging
      BITSWAN_AUTOMATION_URL: https://demo-meeting-form-internal-frontend-2a97-staging.nikita-sandbox.bswn.io
      BITSWAN_DEPLOYMENT_CONTEXT: demo-staging
      BITSWAN_DEPLOYMENT_ID: internal-frontend-demo-staging
      BITSWAN_DEPLOY_CHECKSUM: 80a574ca70a320e749f5d3a3ffcece16a22fcc60
      BITSWAN_DEPLOY_TIME: '2026-06-08T16:14:42.027583Z'
      BITSWAN_GITOPS_DOMAIN: nikita-sandbox.bswn.io
      BITSWAN_URL_PREFIX: https://demo-meeting-form-
      BITSWAN_URL_SUFFIX: .nikita-sandbox.bswn.io
      BITSWAN_URL_TEMPLATE: https://demo-meeting-form-{name}-2a97-staging.nikita-sandbox.bswn.io
      BITSWAN_WORKSPACE_NAME: demo-meeting-form
      KEYCLOAK_ISSUER_URL: https://keycloak.bitswan.ai/realms/master
      KEYCLOAK_REALM: master
      KEYCLOAK_URL: https://keycloak.bitswan.ai
      OAUTH2_PROXY_ALLOWED_GROUPS: /NikitaPlay/admin
      OAUTH2_PROXY_CLIENT_ID: workspace-008e5dc9-ad56-422b-9b7a-38c709e6ebba-internal-frontend-demo-staging-client
      OAUTH2_PROXY_CLIENT_SECRET: 5jhVv2FYM8oWSH4r8grB5U98KsHdRxLM
      OAUTH2_PROXY_CODE_CHALLENGE_METHOD: S256
      OAUTH2_PROXY_COOKIE_REFRESH: 14m
      OAUTH2_PROXY_COOKIE_SECRET: nqxxrX0JXVzuSyVpRIzNCy44WtR0sUWK
      OAUTH2_PROXY_EMAIL_DOMAINS: '*'
      OAUTH2_PROXY_HTTP_ADDRESS: 0.0.0.0:9999
      OAUTH2_PROXY_OIDC_GROUPS_CLAIM: group_membership
      OAUTH2_PROXY_OIDC_ISSUER_URL: https://keycloak.bitswan.ai/realms/master
      OAUTH2_PROXY_PASS_ACCESS_TOKEN: 'true'
      OAUTH2_PROXY_PROVIDER: keycloak-oidc
      OAUTH2_PROXY_REDIRECT_URL: https://demo-meeting-form-internal-frontend-2a97-staging.nikita-sandbox.bswn.io/oauth2/callback
      OAUTH2_PROXY_SCOPE: openid email profile
      OAUTH2_PROXY_SET_XAUTHREQUEST: 'true'
      OAUTH2_PROXY_SKIP_PROVIDER_BUTTON: 'true'
      OAUTH2_PROXY_UPSTREAMS: http://127.0.0.1:8080
      OAUTH_ENABLED: 'true'
      UPDATE_CA_CERTIFICATES: 'true'
    image: internal/demo-meeting-form-demo-internal-frontend:shaff19929f41f3c3a34d4098aa7d1394bb60b3ac98
    labels:
      gitops.automation_name: internal-frontend
      gitops.certs.enabled: 'true'
      gitops.context: demo
      gitops.deployment_id: internal-frontend-demo-staging
      gitops.intended_exposed: 'true'
      gitops.oauth2.enabled: 'true'
      gitops.stage: staging
      gitops.workspace: demo-meeting-form
    networks:
      bitswan_network:
        aliases:
        - demo-meeting-form-internal-frontend-2a97-staging.nikita-sandbox.bswn.io
    restart: always
    ulimits:
      nofile:
        hard: 65536
        soft: 65536
    volumes:
    - /root/.config/bitswan/certauthorities:/usr/local/share/ca-certificates/custom:ro
    - /root/.config/bitswan/workspaces/demo-meeting-form/gitops/80a574ca70a320e749f5d3a3ffcece16a22fcc60:/app/:ro
  demo-meeting-form-internal-frontend-2e40-live-dev:
    container_name: demo-meeting-form-internal-frontend-2e40-live-dev
    environment:
      BITSWAN_ALLOWED_GROUP: /NikitaPlay
      BITSWAN_AUTOMATION_STAGE: live-dev
      BITSWAN_AUTOMATION_URL: https://demo-meeting-form-internal-frontend-2e40-live-dev.nikita-sandbox.bswn.io
      BITSWAN_DEPLOYMENT_CONTEXT: demo-wt-demo-new-live-dev
      BITSWAN_DEPLOYMENT_ID: internal-frontend-wt-demo-new-demo-live-dev
      BITSWAN_DEPLOY_CHECKSUM: live-dev
      BITSWAN_DEPLOY_TIME: '2026-06-08T16:14:42.740729Z'
      BITSWAN_GITOPS_DOMAIN: nikita-sandbox.bswn.io
      BITSWAN_URL_PREFIX: https://demo-meeting-form-
      BITSWAN_URL_SUFFIX: .nikita-sandbox.bswn.io
      BITSWAN_URL_TEMPLATE: https://demo-meeting-form-{name}-2e40-live-dev.nikita-sandbox.bswn.io
      BITSWAN_WORKSPACE_NAME: demo-meeting-form
      KEYCLOAK_ISSUER_URL: https://keycloak.bitswan.ai/realms/master
      KEYCLOAK_REALM: master
      KEYCLOAK_URL: https://keycloak.bitswan.ai
      OAUTH2_PROXY_ALLOWED_GROUPS: /NikitaPlay/admin
      OAUTH2_PROXY_CLIENT_ID: workspace-008e5dc9-ad56-422b-9b7a-38c709e6ebba-internal-frontend-wt-demo-new-demo-live-dev-client
      OAUTH2_PROXY_CLIENT_SECRET: v7XsEPa9EgFC9IpnUCMXp0lCRaV4N2RE
      OAUTH2_PROXY_CODE_CHALLENGE_METHOD: S256
      OAUTH2_PROXY_COOKIE_REFRESH: 14m
      OAUTH2_PROXY_COOKIE_SECRET: nqxxrX0JXVzuSyVpRIzNCy44WtR0sUWK
      OAUTH2_PROXY_EMAIL_DOMAINS: '*'
      OAUTH2_PROXY_HTTP_ADDRESS: 0.0.0.0:9999
      OAUTH2_PROXY_OIDC_GROUPS_CLAIM: group_membership
      OAUTH2_PROXY_OIDC_ISSUER_URL: https://keycloak.bitswan.ai/realms/master
      OAUTH2_PROXY_PASS_ACCESS_TOKEN: 'true'
      OAUTH2_PROXY_PROVIDER: keycloak-oidc
      OAUTH2_PROXY_REDIRECT_URL: https://demo-meeting-form-internal-frontend-2e40-live-dev.nikita-sandbox.bswn.io/oauth2/callback
      OAUTH2_PROXY_SCOPE: openid email profile
      OAUTH2_PROXY_SET_XAUTHREQUEST: 'true'
      OAUTH2_PROXY_SKIP_PROVIDER_BUTTON: 'true'
      OAUTH2_PROXY_UPSTREAMS: http://127.0.0.1:8080
      OAUTH_ENABLED: 'true'
      POSTGRES_DB: postgres_wt_demo_new
      UPDATE_CA_CERTIFICATES: 'true'
    image: internal/demo-meeting-form-demo-internal-frontend:shaff19929f41f3c3a34d4098aa7d1394bb60b3ac98
    labels:
      gitops.automation_name: internal-frontend
      gitops.certs.enabled: 'true'
      gitops.context: wt-demo-new-demo
      gitops.deployment_id: internal-frontend-wt-demo-new-demo-live-dev
      gitops.intended_exposed: 'true'
      gitops.oauth2.enabled: 'true'
      gitops.stage: live-dev
      gitops.workspace: demo-meeting-form
    networks:
      bitswan_network:
        aliases:
        - demo-meeting-form-internal-frontend-2e40-live-dev.nikita-sandbox.bswn.io
    restart: always
    ulimits:
      nofile:
        hard: 65536
        soft: 65536
    volumes:
    - /root/.config/bitswan/certauthorities:/usr/local/share/ca-certificates/custom:ro
    - /root/.config/bitswan/workspaces/demo-meeting-form/workspace/worktrees/demo-new/demo/internal-frontend:/app/:ro
  minio:
    command: server /data --console-address :9001
    container_name: demo-meeting-form__minio
    env_file:
    - /gitops/secrets/minio
    environment:
      BITSWAN_AUTOMATION_URL: https://demo-meeting-form-minio.nikita-sandbox.bswn.io
      OAUTH2_PROXY_CLIENT_ID: workspace-008e5dc9-ad56-422b-9b7a-38c709e6ebba-code-server-client
      OAUTH2_PROXY_CLIENT_SECRET: UmvndhA9ohLVa2jtKxy31asm4CzFLOIn
      OAUTH2_PROXY_CODE_CHALLENGE_METHOD: S256
      OAUTH2_PROXY_COOKIE_SECRET: nqxxrX0JXVzuSyVpRIzNCy44WtR0sUWK
      OAUTH2_PROXY_EMAIL_DOMAINS: '*'
      OAUTH2_PROXY_HTTP_ADDRESS: 0.0.0.0:9999
      OAUTH2_PROXY_MQTT_ALLOWED_GROUPS_TOPIC: /groups
      OAUTH2_PROXY_OIDC_GROUPS_CLAIM: group_membership
      OAUTH2_PROXY_OIDC_ISSUER_URL: https://keycloak.bitswan.ai/realms/master
      OAUTH2_PROXY_PROVIDER: keycloak-oidc
      OAUTH2_PROXY_REDIRECT_URL: https://demo-meeting-form-minio.nikita-sandbox.bswn.io/oauth2/callback
      OAUTH2_PROXY_SCOPE: openid email profile
      OAUTH2_PROXY_SKIP_PROVIDER_BUTTON: 'true'
      OAUTH2_PROXY_UPSTREAMS: http://127.0.0.1:9001
      OAUTH_ENABLED: 'true'
    image: minio/minio:latest
    labels:
      gitops.oauth2.enabled: 'true'
      gitops.oauth2.upstream: http://127.0.0.1:9001
    networks:
    - bitswan_network
    restart: unless-stopped
    volumes:
    - demo-meeting-form-minio-data-data:/data
  minio-dev:
    command: server /data --console-address :9001
    container_name: demo-meeting-form__minio-dev
    env_file:
    - /gitops/secrets/minio-dev
    environment:
      BITSWAN_AUTOMATION_URL: https://demo-meeting-form-minio-dev.nikita-sandbox.bswn.io
      OAUTH2_PROXY_CLIENT_ID: workspace-008e5dc9-ad56-422b-9b7a-38c709e6ebba-code-server-client
      OAUTH2_PROXY_CLIENT_SECRET: UmvndhA9ohLVa2jtKxy31asm4CzFLOIn
      OAUTH2_PROXY_CODE_CHALLENGE_METHOD: S256
      OAUTH2_PROXY_COOKIE_SECRET: nqxxrX0JXVzuSyVpRIzNCy44WtR0sUWK
      OAUTH2_PROXY_EMAIL_DOMAINS: '*'
      OAUTH2_PROXY_HTTP_ADDRESS: 0.0.0.0:9999
      OAUTH2_PROXY_MQTT_ALLOWED_GROUPS_TOPIC: /groups
      OAUTH2_PROXY_OIDC_GROUPS_CLAIM: group_membership
      OAUTH2_PROXY_OIDC_ISSUER_URL: https://keycloak.bitswan.ai/realms/master
      OAUTH2_PROXY_PROVIDER: keycloak-oidc
      OAUTH2_PROXY_REDIRECT_URL: https://demo-meeting-form-minio-dev.nikita-sandbox.bswn.io/oauth2/callback
      OAUTH2_PROXY_SCOPE: openid email profile
      OAUTH2_PROXY_SKIP_PROVIDER_BUTTON: 'true'
      OAUTH2_PROXY_UPSTREAMS: http://127.0.0.1:9001
      OAUTH_ENABLED: 'true'
    image: minio/minio:latest
    labels:
      gitops.oauth2.enabled: 'true'
      gitops.oauth2.upstream: http://127.0.0.1:9001
    networks:
    - bitswan_network
    restart: unless-stopped
    volumes:
    - demo-meeting-form-minio-dev-data-data:/data
  minio-staging:
    command: server /data --console-address :9001
    container_name: demo-meeting-form__minio-staging
    env_file:
    - /gitops/secrets/minio-staging
    environment:
      BITSWAN_AUTOMATION_URL: https://demo-meeting-form-minio-staging.nikita-sandbox.bswn.io
      OAUTH2_PROXY_CLIENT_ID: workspace-008e5dc9-ad56-422b-9b7a-38c709e6ebba-code-server-client
      OAUTH2_PROXY_CLIENT_SECRET: UmvndhA9ohLVa2jtKxy31asm4CzFLOIn
      OAUTH2_PROXY_CODE_CHALLENGE_METHOD: S256
      OAUTH2_PROXY_COOKIE_SECRET: nqxxrX0JXVzuSyVpRIzNCy44WtR0sUWK
      OAUTH2_PROXY_EMAIL_DOMAINS: '*'
      OAUTH2_PROXY_HTTP_ADDRESS: 0.0.0.0:9999
      OAUTH2_PROXY_MQTT_ALLOWED_GROUPS_TOPIC: /groups
      OAUTH2_PROXY_OIDC_GROUPS_CLAIM: group_membership
      OAUTH2_PROXY_OIDC_ISSUER_URL: https://keycloak.bitswan.ai/realms/master
      OAUTH2_PROXY_PROVIDER: keycloak-oidc
      OAUTH2_PROXY_REDIRECT_URL: https://demo-meeting-form-minio-staging.nikita-sandbox.bswn.io/oauth2/callback
      OAUTH2_PROXY_SCOPE: openid email profile
      OAUTH2_PROXY_SKIP_PROVIDER_BUTTON: 'true'
      OAUTH2_PROXY_UPSTREAMS: http://127.0.0.1:9001
      OAUTH_ENABLED: 'true'
    image: minio/minio:latest
    labels:
      gitops.oauth2.enabled: 'true'
      gitops.oauth2.upstream: http://127.0.0.1:9001
    networks:
    - bitswan_network
    restart: unless-stopped
    volumes:
    - demo-meeting-form-minio-staging-data-data:/data
  postgres:
    container_name: demo-meeting-form__postgres
    env_file:
    - /gitops/secrets/postgres
    image: postgres:16
    networks:
    - bitswan_network
    restart: unless-stopped
    volumes:
    - demo-meeting-form-postgres-data-data:/var/lib/postgresql/data
  postgres-dev:
    container_name: demo-meeting-form__postgres-dev
    env_file:
    - /gitops/secrets/postgres-dev
    image: postgres:16
    networks:
    - bitswan_network
    restart: unless-stopped
    volumes:
    - demo-meeting-form-postgres-dev-data-data:/var/lib/postgresql/data
  postgres-dev-pgadmin:
    container_name: demo-meeting-form__postgres-dev-pgadmin
    env_file:
    - /gitops/secrets/postgres-dev
    environment:
      BITSWAN_AUTOMATION_URL: https://demo-meeting-form-postgres-dev.nikita-sandbox.bswn.io
      OAUTH2_PROXY_CLIENT_ID: workspace-008e5dc9-ad56-422b-9b7a-38c709e6ebba-code-server-client
      OAUTH2_PROXY_CLIENT_SECRET: UmvndhA9ohLVa2jtKxy31asm4CzFLOIn
      OAUTH2_PROXY_CODE_CHALLENGE_METHOD: S256
      OAUTH2_PROXY_COOKIE_SECRET: nqxxrX0JXVzuSyVpRIzNCy44WtR0sUWK
      OAUTH2_PROXY_EMAIL_DOMAINS: '*'
      OAUTH2_PROXY_HTTP_ADDRESS: 0.0.0.0:9999
      OAUTH2_PROXY_MQTT_ALLOWED_GROUPS_TOPIC: /groups
      OAUTH2_PROXY_OIDC_GROUPS_CLAIM: group_membership
      OAUTH2_PROXY_OIDC_ISSUER_URL: https://keycloak.bitswan.ai/realms/master
      OAUTH2_PROXY_PROVIDER: keycloak-oidc
      OAUTH2_PROXY_REDIRECT_URL: https://demo-meeting-form-postgres-dev.nikita-sandbox.bswn.io/oauth2/callback
      OAUTH2_PROXY_SCOPE: openid email profile
      OAUTH2_PROXY_SKIP_PROVIDER_BUTTON: 'true'
      OAUTH2_PROXY_UPSTREAMS: http://127.0.0.1:80
      OAUTH_ENABLED: 'true'
    image: dpage/pgadmin4:latest
    labels:
      gitops.oauth2.enabled: 'true'
      gitops.oauth2.upstream: http://127.0.0.1:80
    networks:
    - bitswan_network
    restart: unless-stopped
    volumes:
    - /gitops/secrets/pgadmin-servers.json:/pgadmin4/servers.json:ro
  postgres-pgadmin:
    container_name: demo-meeting-form__postgres-pgadmin
    env_file:
    - /gitops/secrets/postgres
    environment:
      BITSWAN_AUTOMATION_URL: https://demo-meeting-form-postgres.nikita-sandbox.bswn.io
      OAUTH2_PROXY_CLIENT_ID: workspace-008e5dc9-ad56-422b-9b7a-38c709e6ebba-code-server-client
      OAUTH2_PROXY_CLIENT_SECRET: UmvndhA9ohLVa2jtKxy31asm4CzFLOIn
      OAUTH2_PROXY_CODE_CHALLENGE_METHOD: S256
      OAUTH2_PROXY_COOKIE_SECRET: nqxxrX0JXVzuSyVpRIzNCy44WtR0sUWK
      OAUTH2_PROXY_EMAIL_DOMAINS: '*'
      OAUTH2_PROXY_HTTP_ADDRESS: 0.0.0.0:9999
      OAUTH2_PROXY_MQTT_ALLOWED_GROUPS_TOPIC: /groups
      OAUTH2_PROXY_OIDC_GROUPS_CLAIM: group_membership
      OAUTH2_PROXY_OIDC_ISSUER_URL: https://keycloak.bitswan.ai/realms/master
      OAUTH2_PROXY_PROVIDER: keycloak-oidc
      OAUTH2_PROXY_REDIRECT_URL: https://demo-meeting-form-postgres.nikita-sandbox.bswn.io/oauth2/callback
      OAUTH2_PROXY_SCOPE: openid email profile
      OAUTH2_PROXY_SKIP_PROVIDER_BUTTON: 'true'
      OAUTH2_PROXY_UPSTREAMS: http://127.0.0.1:80
      OAUTH_ENABLED: 'true'
    image: dpage/pgadmin4:latest
    labels:
      gitops.oauth2.enabled: 'true'
      gitops.oauth2.upstream: http://127.0.0.1:80
    networks:
    - bitswan_network
    restart: unless-stopped
    volumes:
    - /gitops/secrets/pgadmin-servers.json:/pgadmin4/servers.json:ro
  postgres-staging:
    container_name: demo-meeting-form__postgres-staging
    env_file:
    - /gitops/secrets/postgres-staging
    image: postgres:16
    networks:
    - bitswan_network
    restart: unless-stopped
    volumes:
    - demo-meeting-form-postgres-staging-data-data:/var/lib/postgresql/data
  postgres-staging-pgadmin:
    container_name: demo-meeting-form__postgres-staging-pgadmin
    env_file:
    - /gitops/secrets/postgres-staging
    environment:
      BITSWAN_AUTOMATION_URL: https://demo-meeting-form-postgres-staging.nikita-sandbox.bswn.io
      OAUTH2_PROXY_CLIENT_ID: workspace-008e5dc9-ad56-422b-9b7a-38c709e6ebba-code-server-client
      OAUTH2_PROXY_CLIENT_SECRET: UmvndhA9ohLVa2jtKxy31asm4CzFLOIn
      OAUTH2_PROXY_CODE_CHALLENGE_METHOD: S256
      OAUTH2_PROXY_COOKIE_SECRET: nqxxrX0JXVzuSyVpRIzNCy44WtR0sUWK
      OAUTH2_PROXY_EMAIL_DOMAINS: '*'
      OAUTH2_PROXY_HTTP_ADDRESS: 0.0.0.0:9999
      OAUTH2_PROXY_MQTT_ALLOWED_GROUPS_TOPIC: /groups
      OAUTH2_PROXY_OIDC_GROUPS_CLAIM: group_membership
      OAUTH2_PROXY_OIDC_ISSUER_URL: https://keycloak.bitswan.ai/realms/master
      OAUTH2_PROXY_PROVIDER: keycloak-oidc
      OAUTH2_PROXY_REDIRECT_URL: https://demo-meeting-form-postgres-staging.nikita-sandbox.bswn.io/oauth2/callback
      OAUTH2_PROXY_SCOPE: openid email profile
      OAUTH2_PROXY_SKIP_PROVIDER_BUTTON: 'true'
      OAUTH2_PROXY_UPSTREAMS: http://127.0.0.1:80
      OAUTH_ENABLED: 'true'
    image: dpage/pgadmin4:latest
    labels:
      gitops.oauth2.enabled: 'true'
      gitops.oauth2.upstream: http://127.0.0.1:80
    networks:
    - bitswan_network
    restart: unless-stopped
    volumes:
    - /gitops/secrets/pgadmin-servers.json:/pgadmin4/servers.json:ro
version: '3'
volumes:
  demo-meeting-form-minio-data-data: null
  demo-meeting-form-minio-dev-data-data: null
  demo-meeting-form-minio-staging-data-data: null
  demo-meeting-form-postgres-data-data: null
  demo-meeting-form-postgres-dev-data-data: null
  demo-meeting-form-postgres-staging-data-data: null
