networks:
  bitswan_network:
    external: true
services:
  demo-meeting-form-backend-0f13-live-dev:
    container_name: demo-meeting-form-backend-0f13-live-dev
    env_file:
    - /gitops/secrets/postgres-dev
    - /gitops/secrets/minio-dev
    environment:
      BITSWAN_ALLOWED_GROUP: /NikitaPlay
      BITSWAN_AUTOMATION_STAGE: live-dev
      BITSWAN_AUTOMATION_URL: https://demo-meeting-form-backend-0f13-live-dev.nikita-sandbox.bswn.io
      BITSWAN_DEPLOYMENT_CONTEXT: demo-wt-demo-live-dev
      BITSWAN_DEPLOYMENT_ID: backend-wt-demo-demo-live-dev
      BITSWAN_DEPLOY_CHECKSUM: live-dev
      BITSWAN_DEPLOY_TIME: '2026-06-04T16:53:04.134723Z'
      BITSWAN_GITOPS_DOMAIN: nikita-sandbox.bswn.io
      BITSWAN_URL_PREFIX: https://demo-meeting-form-
      BITSWAN_URL_SUFFIX: .nikita-sandbox.bswn.io
      BITSWAN_URL_TEMPLATE: https://demo-meeting-form-{name}-0f13-live-dev.nikita-sandbox.bswn.io
      BITSWAN_WORKSPACE_NAME: demo-meeting-form
      KEYCLOAK_ISSUER_URL: https://keycloak.bitswan.ai/realms/master
      KEYCLOAK_REALM: master
      KEYCLOAK_URL: https://keycloak.bitswan.ai
      POSTGRES_DB: postgres_wt_demo
      UPDATE_CA_CERTIFICATES: 'true'
    image: internal/demo-meeting-form-demo-backend:sha8269d38f3de691c1ed1a4247a99777aa681d77dd
    labels:
      gitops.automation_name: backend
      gitops.certs.enabled: 'true'
      gitops.context: wt-demo-demo
      gitops.deployment_id: backend-wt-demo-demo-live-dev
      gitops.intended_exposed: 'true'
      gitops.stage: live-dev
      gitops.workspace: demo-meeting-form
    networks:
      bitswan_network:
        aliases:
        - demo-meeting-form-backend-0f13-live-dev.nikita-sandbox.bswn.io
    restart: always
    ulimits:
      nofile:
        hard: 65536
        soft: 65536
    volumes:
    - /root/.config/bitswan/certauthorities:/usr/local/share/ca-certificates/custom:ro
    - /root/.config/bitswan/workspaces/demo-meeting-form/workspace/worktrees/demo/demo/backend:/app/:ro
  demo-meeting-form-internal-frontend-0f13-live-dev:
    container_name: demo-meeting-form-internal-frontend-0f13-live-dev
    environment:
      BITSWAN_ALLOWED_GROUP: /NikitaPlay
      BITSWAN_AUTOMATION_STAGE: live-dev
      BITSWAN_AUTOMATION_URL: https://demo-meeting-form-internal-frontend-0f13-live-dev.nikita-sandbox.bswn.io
      BITSWAN_DEPLOYMENT_CONTEXT: demo-wt-demo-live-dev
      BITSWAN_DEPLOYMENT_ID: internal-frontend-wt-demo-demo-live-dev
      BITSWAN_DEPLOY_CHECKSUM: live-dev
      BITSWAN_DEPLOY_TIME: '2026-06-04T16:53:04.368756Z'
      BITSWAN_GITOPS_DOMAIN: nikita-sandbox.bswn.io
      BITSWAN_URL_PREFIX: https://demo-meeting-form-
      BITSWAN_URL_SUFFIX: .nikita-sandbox.bswn.io
      BITSWAN_URL_TEMPLATE: https://demo-meeting-form-{name}-0f13-live-dev.nikita-sandbox.bswn.io
      BITSWAN_WORKSPACE_NAME: demo-meeting-form
      KEYCLOAK_ISSUER_URL: https://keycloak.bitswan.ai/realms/master
      KEYCLOAK_REALM: master
      KEYCLOAK_URL: https://keycloak.bitswan.ai
      OAUTH2_PROXY_ALLOWED_GROUPS: /NikitaPlay/admin
      OAUTH2_PROXY_CLIENT_ID: workspace-008e5dc9-ad56-422b-9b7a-38c709e6ebba-internal-frontend-wt-demo-demo-live-dev-client
      OAUTH2_PROXY_CLIENT_SECRET: qzkkMI1DdAU1FPXoBdDxO6kaBRliMUtz
      OAUTH2_PROXY_CODE_CHALLENGE_METHOD: S256
      OAUTH2_PROXY_COOKIE_REFRESH: 14m
      OAUTH2_PROXY_COOKIE_SECRET: nqxxrX0JXVzuSyVpRIzNCy44WtR0sUWK
      OAUTH2_PROXY_EMAIL_DOMAINS: '*'
      OAUTH2_PROXY_HTTP_ADDRESS: 0.0.0.0:9999
      OAUTH2_PROXY_OIDC_GROUPS_CLAIM: group_membership
      OAUTH2_PROXY_OIDC_ISSUER_URL: https://keycloak.bitswan.ai/realms/master
      OAUTH2_PROXY_PASS_ACCESS_TOKEN: 'true'
      OAUTH2_PROXY_PROVIDER: keycloak-oidc
      OAUTH2_PROXY_REDIRECT_URL: https://demo-meeting-form-internal-frontend-0f13-live-dev.nikita-sandbox.bswn.io/oauth2/callback
      OAUTH2_PROXY_SCOPE: openid email profile
      OAUTH2_PROXY_SET_XAUTHREQUEST: 'true'
      OAUTH2_PROXY_SKIP_PROVIDER_BUTTON: 'true'
      OAUTH2_PROXY_UPSTREAMS: http://127.0.0.1:8080
      OAUTH_ENABLED: 'true'
      POSTGRES_DB: postgres_wt_demo
      UPDATE_CA_CERTIFICATES: 'true'
    image: internal/demo-meeting-form-demo-internal-frontend:shaff19929f41f3c3a34d4098aa7d1394bb60b3ac98
    labels:
      gitops.automation_name: internal-frontend
      gitops.certs.enabled: 'true'
      gitops.context: wt-demo-demo
      gitops.deployment_id: internal-frontend-wt-demo-demo-live-dev
      gitops.intended_exposed: 'true'
      gitops.oauth2.enabled: 'true'
      gitops.stage: live-dev
      gitops.workspace: demo-meeting-form
    networks:
      bitswan_network:
        aliases:
        - demo-meeting-form-internal-frontend-0f13-live-dev.nikita-sandbox.bswn.io
    restart: always
    ulimits:
      nofile:
        hard: 65536
        soft: 65536
    volumes:
    - /root/.config/bitswan/certauthorities:/usr/local/share/ca-certificates/custom:ro
    - /root/.config/bitswan/workspaces/demo-meeting-form/workspace/worktrees/demo/demo/internal-frontend:/app/:ro
  minio-dev:
    command: server /data --console-address :9001
    container_name: demo-meeting-form__minio-dev
    env_file:
    - /gitops/secrets/minio-dev
    environment:
      BITSWAN_AUTOMATION_URL: https://demo-meeting-form-minio-dev.nikita-sandbox.bswn.io
      OAUTH2_PROXY_CLIENT_ID: workspace-008e5dc9-ad56-422b-9b7a-38c709e6ebba-code-server-client
      OAUTH2_PROXY_CLIENT_SECRET: UmvndhA9ohLVa2jtKxy31asm4CzFLOIn
      OAUTH2_PROXY_CODE_CHALLENGE_METHOD: S256
      OAUTH2_PROXY_COOKIE_SECRET: nqxxrX0JXVzuSyVpRIzNCy44WtR0sUWK
      OAUTH2_PROXY_EMAIL_DOMAINS: '*'
      OAUTH2_PROXY_HTTP_ADDRESS: 0.0.0.0:9999
      OAUTH2_PROXY_MQTT_ALLOWED_GROUPS_TOPIC: /groups
      OAUTH2_PROXY_OIDC_GROUPS_CLAIM: group_membership
      OAUTH2_PROXY_OIDC_ISSUER_URL: https://keycloak.bitswan.ai/realms/master
      OAUTH2_PROXY_PROVIDER: keycloak-oidc
      OAUTH2_PROXY_REDIRECT_URL: https://demo-meeting-form-minio-dev.nikita-sandbox.bswn.io/oauth2/callback
      OAUTH2_PROXY_SCOPE: openid email profile
      OAUTH2_PROXY_SKIP_PROVIDER_BUTTON: 'true'
      OAUTH2_PROXY_UPSTREAMS: http://127.0.0.1:9001
      OAUTH_ENABLED: 'true'
    image: minio/minio:latest
    labels:
      gitops.oauth2.enabled: 'true'
      gitops.oauth2.upstream: http://127.0.0.1:9001
    networks:
    - bitswan_network
    restart: unless-stopped
    volumes:
    - demo-meeting-form-minio-dev-data-data:/data
  postgres-dev:
    container_name: demo-meeting-form__postgres-dev
    env_file:
    - /gitops/secrets/postgres-dev
    image: postgres:16
    networks:
    - bitswan_network
    restart: unless-stopped
    volumes:
    - demo-meeting-form-postgres-dev-data-data:/var/lib/postgresql/data
  postgres-dev-pgadmin:
    container_name: demo-meeting-form__postgres-dev-pgadmin
    env_file:
    - /gitops/secrets/postgres-dev
    environment:
      BITSWAN_AUTOMATION_URL: https://demo-meeting-form-postgres-dev.nikita-sandbox.bswn.io
      OAUTH2_PROXY_CLIENT_ID: workspace-008e5dc9-ad56-422b-9b7a-38c709e6ebba-code-server-client
      OAUTH2_PROXY_CLIENT_SECRET: UmvndhA9ohLVa2jtKxy31asm4CzFLOIn
      OAUTH2_PROXY_CODE_CHALLENGE_METHOD: S256
      OAUTH2_PROXY_COOKIE_SECRET: nqxxrX0JXVzuSyVpRIzNCy44WtR0sUWK
      OAUTH2_PROXY_EMAIL_DOMAINS: '*'
      OAUTH2_PROXY_HTTP_ADDRESS: 0.0.0.0:9999
      OAUTH2_PROXY_MQTT_ALLOWED_GROUPS_TOPIC: /groups
      OAUTH2_PROXY_OIDC_GROUPS_CLAIM: group_membership
      OAUTH2_PROXY_OIDC_ISSUER_URL: https://keycloak.bitswan.ai/realms/master
      OAUTH2_PROXY_PROVIDER: keycloak-oidc
      OAUTH2_PROXY_REDIRECT_URL: https://demo-meeting-form-postgres-dev.nikita-sandbox.bswn.io/oauth2/callback
      OAUTH2_PROXY_SCOPE: openid email profile
      OAUTH2_PROXY_SKIP_PROVIDER_BUTTON: 'true'
      OAUTH2_PROXY_UPSTREAMS: http://127.0.0.1:80
      OAUTH_ENABLED: 'true'
    image: dpage/pgadmin4:latest
    labels:
      gitops.oauth2.enabled: 'true'
      gitops.oauth2.upstream: http://127.0.0.1:80
    networks:
    - bitswan_network
    restart: unless-stopped
    volumes:
    - /gitops/secrets/pgadmin-servers.json:/pgadmin4/servers.json:ro
version: '3'
volumes:
  demo-meeting-form-minio-dev-data-data: null
  demo-meeting-form-postgres-dev-data-data: null
