[deployment]
id = "cda6a43c-420a-411d-beb1-8e755d927a86"
image = "internal/internal-frontend:sha85dcfbd49c923c4f2ca387d3041e22062dac4d5a"

[expose_to]
dev = ["/admin"]
staging = ["/admin"]
production = ["/admin"]
