[deployment]
image = "internal/internal-frontend:shadc58a736deb86302274957a16b967bda2e3360b9"
id = "6123c9c8-e70d-46ca-94a2-2df40ed11995"

[expose_to]
dev = [ "/admin" ]
staging = [ "/admin" ]
production = [ "/admin" ]
