[deployment]
image = "internal/demo-registration-form-demo-backend:sha9832753718484dce98f02b65dce65cad5f74aae9"
expose = true
id = "248778ab-62aa-46ac-bac1-16b4c40570c0"

[services.postgres]
enabled = true

[services.minio]
enabled = true
